name: nlp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  langchain:
  langchain_community: 
  langchain_openai: 
  langchain_google:
  sherpa_onnx:
  get_it: ^9.2.1
  shimmer: ^3.0.0
  translator: ^1.0.4+1
  # audio_waveforms: ^2.0.2
  path_provider: ^2.1.6
  permission_handler: ^12.0.3
  ffmpeg_kit_flutter_new: ^4.2.1
  record: ^6.2.1
  # media_kit: ^1.2.6
  # media_kit_video: ^1.2.0
  # media_kit_libs_linux: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  image_path: "assets/aleppo_ai.png"
  adaptive_icon_background: "#1D6F8F"  # Using the dark blue color code
  adaptive_icon_foreground: "assets/aleppo_ai.png"

flutter:
  uses-material-design: true

  assets:
    - assets/tokens.txt
    - assets/decoder.int8.onnx
    # - assets/decoder.onnx
    - assets/encoder.int8.onnx
    - assets/encoder.int8.onnx.data
    - assets/faculties.jsonl
    - assets/aleppo_ai.png
    - assets/me.wav
    - assets/me.m4a
    - assets/me2.m4a
    - assets/me3.m4a
    - assets/informatics.jsonl